### ISSUE TITLE
About 'vision transformer' in framework of CF-ViT

### ISSUE THREAD

**Issue by kun-dragon** [ChenMnZ/CF-ViT#1]
Thanks for sharing you work.
        In you paper, there are two 'vision transformer' blue rectangles in the framework picture.  Do they use same network and share same parameters?   
![cf-vit](https://user-images.githubusercontent.com/35193162/203940539-1f3cf4d8-61b3-4fba-8989-941ecfa28fbc.png)

**Comment by ChenMnZ** [comment]
Yes, the two 'vision transformer'  in the framework share the same parameters except for the position embedding.
