### ISSUE TITLE
self.informative_selection = False

### ISSUE THREAD

**Issue by TInaWangxue** [ChenMnZ/CF-ViT#10]
![Uploading image.png…]()
你好，请问这里设置self.informative_selection = False，导致训练的时候并没有进行Informative Region Identification.这里我是不是应该修改成True？

**Comment by ChenMnZ** [comment]
无需修改，此处是一个训练trick,前200epoch设为False，后100epoch设置为True。
代码中有实现：https://github.com/ChenMnZ/CF-ViT/blob/84a05ddaccfce646973a6bbe1fff6c4575761d6c/main_deit.py#L375
论文中也有提及：
![image](https://github.com/ChenMnZ/CF-ViT/assets/57585796/dcace3c7-9179-4801-aadd-0238d90a560f)

**Comment by TInaWangxue** [comment]
好的，不好意思，我没注意到
