### ISSUE TITLE
About patch split in the fine stage

### ISSUE THREAD

**Issue by shua-chen** [ChenMnZ/CF-ViT#3]
In fine stage, you further split a patch into 2*2 patches. So, the token's dim decreases to 1/4 and it doesn't match the dim in original ViT. For example, a patch is 16,16,3, after splitting a patch is 8,8,3. How do you solve this problem?

**Comment by ChenMnZ** [comment]
In our approach, we maintain a fixed patch dimension while varying the number of embedded tokens by resizing input images. This process is equivalent to directly changing the patch dimension but has the advantage of facilitating parameter sharing in the patch embedding layer.

For example, suppose the original input image has a resolution of 224x224 and a patch dimension of 16x16. During the coarse stage, we downsize the input image to 112x112. During the fine stage, we use the original 224x224 images. We then select informative tokens from the embed result of the 224x224 resolution and concatenate them with uninformative tokens from the embed result of the 112x112 resolution.

The code corresponding to our approach can be found in lines 211-240 of the [models_deit.py](https://github.com/ChenMnZ/CF-ViT/blob/main/deit/models_deit.py) file.

**Comment by shua-chen** [comment]
> 

Thank u. I get it
