### ISSUE TITLE
with model

### ISSUE THREAD

**Issue by WunnH** [ChenMnZ/CF-ViT#4]
Hello, thank you very much for your excellent work. When I tried to reproduce the code following the steps you provided and set the model as 'cf_deit_small', I encountered the following error: "RuntimeError: Unknown model (cf_deit_small)". After debugging, I found that the function "register_model" in "registry.py" does not include 'cf_deit_small'. Could you please let me know if there is any important part that I might have overlooked?

**Comment by ChenMnZ** [comment]
The 'cf_deit_small' model has been registered on https://github.com/ChenMnZ/CF-ViT/blob/507d19d6cbab8c5594dc6f2e0e984c994c15f651/deit/models_deit.py#L315
I have just tested the released code and script, and it ran successfully. You may need to provide more details about the script you ran.

**Comment by WunnH** [comment]
Hello，I provided code error information：
> Traceback (most recent call last):
  File "D:\my_ideal\CF_ViT_main\main_deit.py", line 438, in <module>
    main(args)
  File "D:\my_ideal\CF_ViT_main\main_deit.py", line 249, in main
    model = create_model(
  File "D:\my_ideal\CF_ViT_main\timm\models\factory.py", line 55, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (cf_deit_small)
Creating model: cf_deit_small

**Comment by WunnH** [comment]
![1680938769(1)](https://user-images.githubusercontent.com/118161355/230709251-b162859a-9f14-41dc-bdcf-7c0c94777585.jpg)
Hello, I provided more information and questions about the error. There is indeed "models_deit" in the "def register_model" function, but when I run the main function, I still encounter the same error as before. This problem has been bothering me for many days. I would be very grateful if you could reply.
![1680939050(1)](https://user-images.githubusercontent.com/118161355/230709386-76cc6fd3-f400-4a9c-b403-8b0ef5734d70.jpg)

**Comment by ChenMnZ** [comment]
To use `create_model` in `main_deit.py`, make sure you have successfully imported `deit.models_deit`. Alternatively, you can create the model by calling the model function directly. For instance, you can replace `model = create_model****` in `main_deit.py` with `model = deit.models_deit.cf_deit_small()`.

**Comment by WunnH** [comment]
Thank you very much, my problem has been solved, thank you again for your excellent work.
