### ISSUE TITLE
Training setting for confidence threshold η

### ISSUE THREAD

**Issue by fyaft2012** [ChenMnZ/CF-ViT#5]
Hi @ChenMnZ , thanks for your excellent work! Wolud you please guide me how to set the confidence threshould η, and the start epoch number (which is set to 200 in your paper)? Because I cannot find any config file to do it, I want to learn more about these settings, thanks.

**Comment by ChenMnZ** [comment]
1. Confidence threshold: During the training process, we use a default value of $\eta=1$ for the fine inference stage for all images, and we don't explicitly set $\eta$ in the code for training. However, we do provide a set of $\eta$ values for inference, which you can adjust by modifying the $threshold$ parameter of the $forward_early_exit$ function. You can find this parameter at https://github.com/ChenMnZ/CF-ViT/blob/507d19d6cbab8c5594dc6f2e0e984c994c15f651/deit/models_deit.py#L250.

2. Start epoch: The start epoch is determined in the code at https://github.com/ChenMnZ/CF-ViT/blob/507d19d6cbab8c5594dc6f2e0e984c994c15f651/main_deit.py#L387.

**Comment by ChenMnZ** [comment]
1. Confidence threshold: During the training process, we use a default value of $\eta=1$ for the fine inference stage for all images, and we don't explicitly set $\eta$ in the code for training. However, we do provide a set of $\eta$ values for inference, which you can adjust by modifying the `threshold` parameter of the `forward_early_exit` function. You can find this parameter at https://github.com/ChenMnZ/CF-ViT/blob/507d19d6cbab8c5594dc6f2e0e984c994c15f651/deit/models_deit.py#L250.

2. Start epoch: The start epoch is determined in the code at https://github.com/ChenMnZ/CF-ViT/blob/507d19d6cbab8c5594dc6f2e0e984c994c15f651/main_deit.py#L387.

**Comment by fyaft2012** [comment]
GOt it! Thank you very much for timely answer. I will close this issue.
