### ISSUE TITLE
XX[0] OR XX[1]

### ISSUE THREAD

**Issue by KDAkasa** [ChenMnZ/CF-ViT#7]
May I ask if the XX [0] and XX [1] in your input represent two inputs of the original image

**Comment by ChenMnZ** [comment]
Yes, XX[0] and XX[1] represent the input of coarse stage and fine stage respectively. For example, XX[0] is 112x112 images and XX[1] is 224x224 images. More detail aboult this setting can be found at [issue 3](https://github.com/ChenMnZ/CF-ViT/issues/3#issuecomment-1470101240).

**Comment by KDAkasa** [comment]
Thank you very much for your answer
