### ISSUE TITLE
实验设置

### ISSUE THREAD

**Issue by TInaWangxue** [ChenMnZ/CF-ViT#9]
![image](https://github.com/ChenMnZ/CF-ViT/assets/52588760/c8c7b460-5b23-4214-a337-b0762386bacf)
你好，请问这个实验的设置，您是修改的stride size还是image的H、W从而进行不同tokens的比较，patch size的大小是固定的吗？这部分实验的代码可以分享一下嘛

**Comment by ChenMnZ** [comment]
此处7x7我是直接修改输入图片尺寸为112x112，未保留实验代码，你可以直接通过官网的DeiT代码修改输入图片尺寸进行复现。

**Comment by TInaWangxue** [comment]
好的，谢谢
